### ISSUE TITLE
Please unify the license.

### ISSUE THREAD

**Issue by magnetophon** [sadko4u/tamgamp.lv2#11]
The LICENCE file says GPL3, but the code says GPL3 or later.

Thank you!

**Comment by sadko4u** [comment]
No, LICENSE file says LGPL v3, the header is valid for LGPL:
https://www.gnu.org/licenses/gpl-howto.html

If I'm wrong somewere, please show the files with wrong headers.

**Comment by magnetophon** [comment]
I was reacting to https://github.com/NixOS/nixpkgs/pull/82835#discussion_r439763034
When I read that, I did a quick check, and in the first source file I looked at, I thought I there was no "or later" clause. 
Now I can't find it anymore.

@evils, what did you mean?

**Comment by evils** [comment]
@magnetophon i meant i'm not familiar enough with these licenses to distinguish between a `v3 only` or a `v3 or later` license

comparing the license texts provided by SPDX for [v3 only](https://spdx.org/licenses/LGPL-3.0-only.html#licenseText) and [v3 or later](https://spdx.org/licenses/LGPL-3.0-or-later.html#licenseText)
they are identical

it seems like that distinction is only made in the copyright headers,
the ones used here [(e.g.)](https://github.com/sadko4u/tamgamp.lv2/blob/master/src/tamgamp.lv2/tamgamp.cpp#L12) specify `or later`,
meaning the SPDX license identifier for this work is most likely `LGPL-3.0-or-later` (`lib.licenses.lgpl3Plus` in nixpkgs)

@sadko4u going by [the link you provided](https://www.gnu.org/licenses/gpl-howto.html), as the LGPL is a modifier to the GPL, you should include the license text of the GPLv3 as well

**Comment by sadko4u** [comment]
@evils 
Updated license text: cea341fec3697cfbce0f9c0cc28c1eb693383109

**Comment by evils** [comment]
@sadko4u unfortunately, now github does not detect the license correctly
using the GNU recommended naming of `COPYING` and `COPYING.LESSER` [seems to work correctly](https://github.com/evils/tamgamp.lv2)
if you want to keep the `LICENSE` file you could make that a link to `COPYING.LESSER`

**Comment by sadko4u** [comment]
@evils
Renamed the files 426da74142fcb6b7687a35b2b1dda3392e171b92

**Comment by magnetophon** [comment]
@sadko4u, @evils Thanks!
