### ISSUE TITLE
README improvements

### ISSUE THREAD

**Issue by cyrusadkisson** [sadko4u/tamgamp.lv2#3]
1. The README doesn't really state how tamgamp is any different than guitarix. IMO, what you wrote on the linuxmusicians forum announcement...

```
The key features of this project according to technical requirements were:
Simplicity of the interface, no UI (use generic one), minimum knobs/sliders
Smooth bypass button.
Smooth switch between amplifier models.
Smooth switch between tone control chains.
Smooth knob control without pops and other sound artifacts which allows to apply automation to the plugin.
Normalized output level: different amplifiers should sound almost of the same output loudness with different gain settings.
```
... should be front and center at the top of the README as well.

2. The README should also state that tamgamp does not attempt to do any cab simulation and that the user should use their own.

3. At the top of the README, I would include a picture of it in action. Like this https://imgur.com/a/rR5HJOR

4. It's not _pronounced_ "damage amp", it _rhymes with_ "damage amp".

**Comment by sadko4u** [comment]
Consider looking this:
https://github.com/sadko4u/tamgamp.lv2/blob/github-issue-3/README.md

All is OK now?

**Comment by cyrusadkisson** [comment]
Not quite:

1. The font in the image is hard to read.
2. You haven't selected an amp chain in the image
3. "Preamplifier simulation only, no cabinet/power amplifier simulation is required." sounds like (and was) a product requirement. When talking to the user, it should be more like "Preamplifier simulation only, for simplicity and flexibility. (Use a separate cab simulator.)"
4. This entire block:

> Smooth bypass button.
> Smooth switch between amplifier models.
> Smooth switch between tone control chains.
> Smooth knob control without pops and other sound artifacts which allows to apply automation to the plugin.

can be reduced to

"Smooth bypass/automation. No pops, spikes or clicks."

**Comment by sadko4u** [comment]
Updated screenshot and README. Please verify.

**Comment by cyrusadkisson** [comment]
Looks good!

**Comment by sadko4u** [comment]
Merged changes into **master**
