### ISSUE TITLE
Not recognized by Ardour

### ISSUE THREAD

**Issue by cyrusadkisson** [sadko4u/tamgamp.lv2#4]
Just freshly cloned, built and installed Tamgamp but Ardour can't find it. Is it installing to the wrong directory?

```
Generated TTL files
Installing LV2 plugins to /usr/local/lib/lv2/tamgamp.lv2
mkdir -p /usr/local/lib/lv2/tamgamp.lv2
install /home/cyrus/tamgamp.lv2/.build/tamgamp-lv2.so /usr/local/lib/lv2/tamgamp.lv2
cp /home/cyrus/tamgamp.lv2/.build/ttl/manifest.ttl /home/cyrus/tamgamp.lv2/.build/ttl/tamgamp.ttl /home/cyrus/tamgamp.lv2/.build/ttl/tamgamp_gx.ttl /usr/local/lib/lv2/tamgamp.lv2/
Install OK
```

**Comment by sadko4u** [comment]
By default, plugin installs into '/usr/local/lib/lv2' location.
Some distros like Debian can ignore this location. You need to try to install to '/usr/lib/lv2' instead.

Try to build with:
```
make install PREFIX=/usr
```

**Comment by cyrusadkisson** [comment]
All of my other plugins are installed to /usr/local/lib/lv2 and they are recognized just fine.

I should note that tamgamp shows up in the plugin manager (of Ardour) but any session I have with tamgamp already in the mixer strip gives me the error "Tamgamp not found will use a stub instead" (pharaphrased). 

So why is it in the plugin manager, yet not found in existing sessions?

**Comment by sadko4u** [comment]
> So why is it in the plugin manager, yet not found in existing sessions?

It seems that all is OK with reading LV2 TTL file but bad with loading the *.so file

What does:
```
ldd /usr/local/lib/lv2/tamgamp.lv2/tamgamp-lv2.so
```
show?

**Comment by cyrusadkisson** [comment]
```
cyrus@okcomputer:/usr/local/lib/lv2$ ldd /usr/local/lib/lv2/tamgamp.lv2/tamgamp-lv2.so
	linux-vdso.so.1 (0x00007ffdc07d6000)
	libzita-resampler.so.1 => /lib/x86_64-linux-gnu/libzita-resampler.so.1 (0x00007f663d69b000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f663d4ba000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f663d36b000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f663d350000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f663d15e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f663d903000)
```

**Comment by sadko4u** [comment]
Hmm, all seems to be OK.
Have you tried to run tamgamp.lv2 with jalv host?

```
jalv.qt4 https://github.com/sadko4u/tamgamp.lv2/lv2/tamgamp
```
shows:
![image](https://user-images.githubusercontent.com/12834464/80927505-fc960880-8da6-11ea-9c2f-114802276aee.png)

Don't try jalv.gtk and jalv.gtk3, they crash because of logarithmic controls (AFAIR).

**Comment by sadko4u** [comment]
@cyrusadkisson 
Is the problem solved with latest updates?

**Comment by cyrusadkisson** [comment]
I just reinstalled from scratch and it resolved. Not entirely sure what the issue was, but I doubt anybody else will encounter it, so no use in pursuing it.
