### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by sp-pinkeye** [sadko4u/tamgamp.lv2#5]
I have tried to launch in "jalv", "Carla" and Mixbus and get same result, segmentation fault.
Using Debian 10.

**Comment by sadko4u** [comment]
What jalv you have used? jalv.qt4 or jalv.qt5 works fine.
![image](https://user-images.githubusercontent.com/12834464/81047148-84bd0080-8ec2-11ea-9a78-3c8841c9a5e1.png)

jalv.gtk and jalv.gtk3 crash. That's problem of jalv host that can not handle some controls properly.

**Comment by sub26nico** [comment]
Works here in Mixbus5, Ardour 5 & 6, Carla and Jalv (with Qt- 5), on Debian 10.

**Comment by sadko4u** [comment]
I've created the related issue for jalv host.
@sub26nico do you have the same crash issue with jalv.gtk and jalv.gtk3?

**Comment by sub26nico** [comment]
@sadko4u , it doesn't launch here with  jalv.gtk , jalv.gtk3, and jalv -s. it only opens UI with jalv.qt5

**Comment by brummer10** [comment]
the problem is the entry
`lv2:designation lv2:control`
for nearly any port.
http://lv2plug.in/ns/lv2core#control

> Typically this will be an event port that supports some protocol, for example MIDI or LV2 Atoms.

Remove them from the ttl files will make it work in any host.

**Comment by sadko4u** [comment]
@brummer10 
Thanks, I'll fix it.

**Comment by sadko4u** [comment]
Fixed: 3654e89f0d2ce03474b275f9e1d1cd3003d1ef6a
