### ISSUE TITLE
files in build system owned by root

### ISSUE THREAD

**Issue by brummer10** [sadko4u/tamgamp.lv2#6]
The tittle says it, some files and folders in the build folder been owned by root. Is that really necessary?

**Comment by sadko4u** [comment]
No, that's the result of automated source generation from su. Will fix.

**Comment by sadko4u** [comment]
Don't see any root file owners after git clone. How did you get it?

**Comment by brummer10** [comment]
I run make && sudo make install. Then I realise that the folder /.build/ttl and the file  /.build/tamgamp-lv2.so is owned by root.

**Comment by sadko4u** [comment]
.build is an automatically-created build directory. All files created there are of the same owner who executed the build. This is expected behaviour I think.

**Comment by brummer10** [comment]
That's what I think as well, but here it isn't the case. As pointed out, the folder /.build/ttl and the file /.build/tamgamp-lv2.so is owned by root, the files in /.build/src/ been not. The issue is that the ttl files been created when running make install, hence they be owned by root. So, I end up with files owned by root in my home folder, not very nice!

**Comment by brummer10** [comment]
I've just put a 
`chmod -R 777 $(BUILD_DIR)`
in the makefile install target, after install/cp to resolve that for me.

**Comment by sadko4u** [comment]
Ah, now it's clear. You build files as user and then install them by:
```
sudo make install
```

This patch should fix the problem: 590ced0a1da96ca481a1a719eebdb17f3af472e4

**Comment by brummer10** [comment]
Yes. Thanks for accept my issue. 
Your patch makes it it better, at least the ttl files been 'saved', just, we still end with /.build/tamgamp-lv2.so owned by root after install. By the way, I would prefer to install as user to ~/.lv2, just that would require a hack on your makefile, would be easier when you provide a LIBDIR var as well.

However, I know there are a couple of parameters to set the owner of files for src/dst in the install command in make, but because I'm lazy, I prefer the chmod command.

Still, good work, the amps sounds nice to me.

**Comment by sadko4u** [comment]
> we still end with /.build/tamgamp-lv2.so owned by root after install

Currently it's not easy to fix it. Is it still important for you?

> By the way, I would prefer to install as user to ~/.lv2, just that would require a hack on your makefile

You may override LV2DIR parameter when installing and all should be nice.

**Comment by brummer10** [comment]
> Currently it's not easy to fix it. Is it still important for you?

No, for me, as pointed out, I've fixed it locally. 

> You may override LV2DIR parameter when installing and all should be nice.

That works. Nice.
